name: linkso
description: Url shorter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_theme_switcher: ^2.0.1
  charts_flutter: #^0.11.0 # не обновлено для flutter 2.5
    git:
      url: https://github.com/google/charts
      path: charts_flutter
  cupertino_icons: ^1.0.3
  data_table_2: ^2.1.1
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^3.5.2
  flutter_localizations:
    sdk: flutter
  get: ^4.3.8
  get_storage: ^2.0.3
  glassmorphism: ^3.0.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  retrofit: ^2.0.1
  url_launcher: ^6.0.12
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  lint: ^1.7.2
  retrofit_generator: ^2.0.1+2

flutter:
  uses-material-design: true
  generate: true
  #assets:
  #  - assets/images/