name: linkso
description: Url shorter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charts_flutter: ^0.11.0
  cupertino_icons: ^1.0.3
  data_table_2: ^2.1.1 # под вопросом
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.3.8
  glassmorphism: ^3.0.0
  google_fonts: ^2.1.0
  url_launcher: ^6.0.12
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true
  generate: true
  #assets:
  #  - assets/images/