name: linkso
description: Url shorter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  # animated_theme_switcher: ^2.0.1 # не обновлено для flutter 2.5
  charts_flutter: ^0.12.0
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.4
  data_table_2: ^2.2.0
  dio: ^4.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.3.8
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  intl: ^0.17.0
  json_annotation: ^4.3.0
  retrofit: ^3.0.0
  universal_html: ^2.0.8 # for replace dart:html
  url_launcher: ^6.0.12
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  lint: ^1.7.2
  retrofit_generator: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  #assets:
  #  - assets/images/