// The SVG is the single source for PNG exports and Flutter painter geometry.
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const sharp = require('sharp');

const root = path.resolve(__dirname, '../..');
const client = path.join(root, 'linkso_client');
const check = process.argv.includes('--check');

async function main() {
  const svg = await fs.readFile(path.join(client, 'assets/branding/linkso-logo.svg'), 'utf8');
  assert(!/<(?:image|text)\b/.test(svg), 'The logo must contain vector paths, not raster images or font text.');
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1].split(/\s+/).map(Number);
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((match) => match[1]);
  assert.equal(paths.length, 2, 'Expected the two approved SO contours.');
  const commands = paths.map((data) => {
    const tokens = data.match(/[A-Za-z]|-?\d+(?:\.\d+)?/g);
    const lines = ['    Path()'];
    const types = { M: ['moveTo', 2], L: ['lineTo', 2], C: ['cubicTo', 6], Z: ['close', 0] };
    while (tokens.length) {
      const command = tokens.shift();
      assert(command in types, `Unsupported SVG command: ${command}`);
      const [method, count] = types[command];
      const args = tokens.splice(0, count).map(Number);
      assert(args.length === count && args.every(Number.isFinite));
      lines.push(`      ..${method}(${args.join(', ')})`);
    }
    return lines.join('\n') + ',';
  });
  const geometry = `// Generated by tool/brand/generate.cjs from assets/branding/linkso-logo.svg.
// Do not edit manually; regenerate after changing the SVG.
import 'package:flutter/painting.dart';

const linkSoLogoViewBox = Rect.fromLTWH(${viewBox.join(', ')});

List<Path> createLinkSoLogoPaths() => [
${commands.join('\n')}
];
`;

  async function output(relative, buffer) {
    const target = path.resolve(client, relative);
    assert(target.startsWith(client + path.sep), 'Output must remain inside linkso_client.');
    if (check) {
      const actual = await fs.readFile(target);
      assert(actual.equals(Buffer.from(buffer)), `Stale generated asset: ${relative}`);
    } else {
      await fs.mkdir(path.dirname(target), { recursive: true });
      await fs.writeFile(target, buffer);
    }
  }

  // Generated Dart is intentionally formatted by dart format after generation.
  if (!check) await output('lib/src/core/widgets/linkso_logo_paths.g.dart', geometry);
  else {
    const actual = await fs.readFile(path.join(client, 'lib/src/core/widgets/linkso_logo_paths.g.dart'), 'utf8');
    assert.equal(actual.replace(/\s+/g, ''), geometry.replace(/\s+/g, ''), 'Stale painter geometry.');
  }

  let count = 0;
  async function png(relative, size, { coverage = 1, opaque = false } = {}) {
    const markSize = Math.round(size * coverage);
    const mark = await sharp(Buffer.from(svg), { density: 300 }).resize(markSize, markSize).png().toBuffer();
    const background = opaque ? '#FFFFFF' : { r: 255, g: 255, b: 255, alpha: 0 };
    let result = sharp({ create: { width: size, height: size, channels: 4, background } })
      .composite([{ input: mark, left: Math.floor((size - markSize) / 2), top: Math.floor((size - markSize) / 2) }]);
    if (opaque) result = result.flatten({ background: '#FFFFFF' }).removeAlpha();
    const buffer = await result.png().toBuffer();
    const meta = await sharp(buffer).metadata();
    assert.equal(meta.width, size);
    assert.equal(meta.height, size);
    assert.equal(meta.hasAlpha, !opaque);
    if (!opaque) {
      const pixels = await sharp(buffer).ensureAlpha().raw().toBuffer();
      assert.equal(pixels[3], 0, `Expected a transparent corner: ${relative}`);
      assert.equal(pixels[pixels.length - 1], 0, `Expected a transparent corner: ${relative}`);
    }
    await output(relative, buffer);
    count++;
  }

  await png('assets/branding/linkso-logo.png', 1024);
  await png('assets/branding/linkso-app-icon.png', 1024, { coverage: 0.8, opaque: true });
  await png('web/favicon.png', 32, { coverage: 0.96 });
  await png('web/icons/apple-touch-icon.png', 180, { coverage: 0.8 });
  for (const size of [192, 512]) {
    await png(`web/icons/Icon-${size}.png`, size, { coverage: 0.8 });
  }
  const ios = JSON.parse(await fs.readFile(path.join(client, 'ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json')));
  const iosSizes = new Map(ios.images.map((item) => [item.filename, parseFloat(item.size) * parseFloat(item.scale)]));
  for (const [filename, size] of iosSizes) {
    await png(`ios/Runner/Assets.xcassets/AppIcon.appiconset/${filename}`, size, { coverage: 0.8, opaque: true });
  }
  for (const [density, scale] of [['ldpi', 0.75], ['mdpi', 1], ['hdpi', 1.5], ['xhdpi', 2], ['xxhdpi', 3], ['xxxhdpi', 4]]) {
    await png(`android/app/src/main/res/mipmap-${density}/ic_launcher.png`, 48 * scale, { coverage: 0.8 });
    await png(`android/app/src/main/res/mipmap-${density}/ic_launcher_round.png`, 48 * scale, { coverage: 0.8 });
    // Adaptive foreground stays inside the central safe area of a 108dp layer.
    await png(`android/app/src/main/res/mipmap-${density}/ic_launcher_foreground.png`, 108 * scale, { coverage: 0.56 });
  }
  console.log(`${check ? 'Verified' : 'Generated'} ${count} PNG files and matching Flutter geometry.`);
}

main().catch((error) => { console.error(error.message); process.exitCode = 1; });
