// Generated by tool/brand/generate.cjs from assets/branding/linkso-logo.svg.
// Do not edit manually; regenerate after changing the SVG.
import 'package:flutter/painting.dart';

const linkSoLogoViewBox = Rect.fromLTWH(90, 75, 1080, 1080);

List<Path> createLinkSoLogoPaths() => [
  Path()
    ..moveTo(541, 421)
    ..lineTo(708, 252)
    ..cubicTo(817, 145, 964, 168, 1056, 257)
    ..cubicTo(1174, 371, 1183, 520, 1072, 640)
    ..lineTo(967, 747)
    ..cubicTo(881, 833, 763, 860, 651, 809)
    ..cubicTo(554, 765, 499, 678, 502, 573)
    ..lineTo(628, 607)
    ..cubicTo(639, 661, 670, 692, 714, 704)
    ..cubicTo(760, 719, 801, 705, 837, 668)
    ..lineTo(977, 526)
    ..cubicTo(1024, 478, 1020, 409, 977, 363)
    ..cubicTo(927, 310, 859, 295, 808, 345)
    ..lineTo(686, 459)
    ..close(),
  Path()
    ..moveTo(727, 486)
    ..cubicTo(777, 502, 797, 536, 788, 580)
    ..cubicTo(782, 610, 761, 630, 733, 635)
    ..cubicTo(703, 640, 681, 625, 665, 602)
    ..lineTo(477, 553)
    ..cubicTo(433, 542, 391, 553, 366, 581)
    ..cubicTo(329, 620, 363, 648, 410, 675)
    ..lineTo(521, 737)
    ..cubicTo(546, 753, 575, 789, 617, 815)
    ..cubicTo(642, 879, 624, 944, 568, 989)
    ..cubicTo(471, 1068, 326, 1061, 218, 1007)
    ..cubicTo(142, 969, 103, 916, 110, 846)
    ..cubicTo(115, 797, 150, 767, 195, 769)
    ..cubicTo(236, 770, 260, 803, 253, 842)
    ..cubicTo(244, 880, 288, 903, 337, 914)
    ..cubicTo(387, 926, 439, 921, 469, 895)
    ..cubicTo(499, 869, 486, 843, 451, 823)
    ..lineTo(305, 755)
    ..cubicTo(243, 726, 211, 677, 214, 616)
    ..cubicTo(218, 541, 262, 482, 332, 448)
    ..cubicTo(382, 424, 434, 413, 490, 426)
    ..close(),
];
